 (cd "$(git rev-parse --show-toplevel)" && git apply --3way <<'EOF' 
diff --git a/app.py b/app.py
index 025d6dcd871ad3a9afedb2bfa0cb8ebc8a1ae0f9..c31e426bf52897e1e12f18e733999bc6d9230eee 100644
--- a/app.py
+++ b/app.py
@@ -1,37 +1,9 @@
+"""Thin Streamlit entrypoint.
 
-import streamlit as st
-import pandas as pd
-import numpy as np
-import altair as alt
+Keeps app.py minimal so deployment entrypoints are stable.
+"""
 
-st.set_page_config(page_title="Long Volatility Signal Engine", layout="wide")
+from dashboard import main
 
-st.sidebar.title("⚙️ Configuration")
-api_key = st.sidebar.text_input("InvestDEFY API Key (placeholder only)", type="password")
-hour_run = st.sidebar.selectbox("Simulated Hourly Trigger (UTC)", list(range(24)), index=12)
-
-@st.cache_data
-def load_data():
-    df = pd.read_csv("data/hourly_signals.csv", parse_dates=["time_utc"])
-    df = df.sort_values("time_utc")
-    df["Cumulative PnL"] = df["strangle_pnl"].cumsum()
-    return df
-
-df = load_data()
-
-st.title("📈 Long Volatility Signal Engine (Hourly Triggered)")
-st.markdown("""
-This engine simulates long volatility (strangle-based) trades using hourly signals generated by the Reggie and Ensemble Range models.
-Trade logic assumes entry on signal, 14-day hold to expiry. PnL is pre-computed. 
-""")
-st.subheader("Signal Table")
-st.dataframe(df[["time_utc", "total_signals", "ensemble_predicted_range", "strangle_pnl", "Cumulative PnL"]], use_container_width=True)
-
-st.subheader("💰 Strategy Equity Curve")
-chart = alt.Chart(df).mark_line().encode(
-    x="time_utc:T",
-    y="Cumulative PnL:Q"
-).properties(width=900, height=400)
-st.altair_chart(chart, use_container_width=True)
-
-st.caption("🔄 Built for hourly runtime and can be extended with InvestDEFY API integration.")
+if __name__ == "__main__":
+    main()
 
EOF
)
